import { AcademyMission, AcademyDifficulty } from './academy-types'

export const TUTORIAL_MISSIONS: AcademyMission[] = [
  {
    id: 'T-01',
    title: 'The Quantum Flip',
    description: 'Learn how to invert a qubit\'s state using the quantum equivalent of a NOT gate.',
    difficulty: 'Tutorial',
    prerequisiteId: null,
    initialQubits: 1,
    maxSteps: 1,
    allowedGates: ['X'],
    learningObjective: 'Understand the Pauli-X gate as a bit-flip operation.',
    estimatedMinutes: 2,
  },
  {
    id: 'T-02',
    title: 'Create Superposition',
    description: 'Experience true quantum behavior by putting a qubit into a superposition of 0 and 1.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-01',
    initialQubits: 1,
    maxSteps: 1,
    allowedGates: ['H'],
    learningObjective: 'Creating an equal superposition basis state.',
    estimatedMinutes: 2,
  },
  {
    id: 'T-03',
    title: 'Phase Kickback Intro',
    description: 'Observe how a phase shift affects a superposition state.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-02',
    initialQubits: 1,
    maxSteps: 2,
    allowedGates: ['H', 'Z'],
    learningObjective: 'Understanding relative phase.',
    estimatedMinutes: 3,
  },
  {
    id: 'T-04',
    title: 'The Quantum Toggle',
    description: 'Apply operations in sequence and see how order matters.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-03',
    initialQubits: 1,
    maxSteps: 2,
    allowedGates: ['X', 'H'],
    learningObjective: 'Gate non-commutativity (HX != XH).',
    estimatedMinutes: 3,
  },
  {
    id: 'T-05',
    title: 'First Measurement',
    description: 'Measure a qubit in superposition to collapse its state.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-04',
    initialQubits: 1,
    maxSteps: 2,
    allowedGates: ['H', 'M'],
    learningObjective: 'Measurement and wavefunction collapse.',
    estimatedMinutes: 2,
  },
  {
    id: 'T-06',
    title: 'Two Qubits',
    description: 'Manage a system with two independent qubits.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-05',
    initialQubits: 2,
    maxSteps: 2,
    allowedGates: ['H'],
    learningObjective: 'Handling multi-qubit systems independently.',
    estimatedMinutes: 3,
  },
  {
    id: 'T-07',
    title: 'Create Bell State',
    description: 'Entangle two qubits to create the maximally entangled Bell state.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-06',
    initialQubits: 2,
    maxSteps: 3,
    allowedGates: ['H', 'CNOT'],
    learningObjective: 'Quantum entanglement via CNOT.',
    estimatedMinutes: 5,
  },
  {
    id: 'T-08',
    title: 'Entanglement Proof',
    description: 'Measure the Bell state to prove perfect correlation.',
    difficulty: 'Tutorial',
    prerequisiteId: 'T-07',
    initialQubits: 2,
    maxSteps: 3,
    allowedGates: ['H', 'CNOT', 'M'],
    learningObjective: 'Entanglement implies measurement correlation.',
    estimatedMinutes: 4,
  },
]

export const ACADEMY_MISSIONS: AcademyMission[] = [...TUTORIAL_MISSIONS]

export const DIFFICULTY_LEVELS: AcademyDifficulty[] = ['Tutorial', 'Beginner', 'Intermediate', 'Advanced', 'Expert']
